name: Python application

on:
  push:
    branches: [ "main", "dev"  ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Change directory
        run: cd ./auth
      
      - name: "Setup Python, Poetry and Dependencies"
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: 3.10.13
          poetry-version: 1.7.1

      - name: Run tests with coverage
        run: poetry run pytest tests/
